# Import libraries & File

In [92]:
import warnings
warnings.filterwarnings('ignore')

# Data manip
import pandas as pd
import numpy as np

# Sklearn
from sklearn.model_selection import train_test_split
from sklearn.impute import KNNImputer
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import RobustScaler
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.metrics import r2_score,max_error,mean_absolute_error, mean_squared_error

#Pipeline
from sklearn.pipeline import make_pipeline
from sklearn.compose import make_column_transformer

#Pickle
import pickle

In [93]:
# File opening
data = pd.read_csv("DATA/data.csv") #Put your path file containing the datas to test
df = data.copy()
df=df.drop(["Unnamed: 0"], axis=1, errors='ignore')
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-119.84,36.77,6.0,1853.0,473.0,1397.0,417.0,1.4817,72000.0,INLAND
1,-117.80,33.68,8.0,2032.0,349.0,862.0,340.0,6.9133,274100.0,<1H OCEAN
2,-120.19,36.60,25.0,875.0,214.0,931.0,214.0,1.5536,58300.0,INLAND
3,-118.32,34.10,31.0,622.0,229.0,597.0,227.0,1.5284,200000.0,<1H OCEAN
4,-121.23,37.79,21.0,1922.0,373.0,1130.0,372.0,4.0815,117900.0,INLAND

In [94]:
# imputation function
# replace missing values on total_bedrooms with KNN
knn_imputer = KNNImputer(n_neighbors=4, weights="uniform")
df['total_bedrooms'] = knn_imputer.fit_transform(df[['total_bedrooms']])

In [95]:
# encoding ocean_proximity
df= pd.get_dummies(df, columns=['ocean_proximity'], prefix=["location"])
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,location_<1H OCEAN,location_INLAND,location_ISLAND,location_NEAR BAY,location_NEAR OCEAN
0,-119.84,36.77,6.0,1853.0,473.0,1397.0,417.0,1.4817,72000.0,0,1,0,0,0
1,-117.80,33.68,8.0,2032.0,349.0,862.0,340.0,6.9133,274100.0,1,0,0,0,0
2,-120.19,36.60,25.0,875.0,214.0,931.0,214.0,1.5536,58300.0,0,1,0,0,0
3,-118.32,34.10,31.0,622.0,229.0,597.0,227.0,1.5284,200000.0,1,0,0,0,0
4,-121.23,37.79,21.0,1922.0,373.0,1130.0,372.0,4.0815,117900.0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16507,-121.90,39.59,20.0,1465.0,278.0,745.0,250.0,3.0625,93800.0,0,1,0,0,0
16508,-122.25,38.11,49.0,2365.0,504.0,1131.0,458.0,2.6133,103100.0,0,0,0,1,0
16509,-121.22,38.92,19.0,2531.0,461.0,1206.0,429.0,4.4958,192600.0,0,1,0,0,0
16510,-118.14,34.16,39.0,2776.0,840.0,2546.0,773.0,2.5750,153500.0,1,0,0,0,0
16511,-124.13,40.80,31.0,2152.0,462.0,1259.0,420.0,2.2478,81100.0,0,0,0,0,1

In [96]:
trainset, testset = train_test_split(df, test_size=0.3, random_state=0)
X_train, y_train, X_test, y_test = preprocessing(trainset, testset)

In [97]:
model_pipeline1 = make_pipeline(StandardScaler(), KNeighborsRegressor())

In [98]:
model_pipeline1.fit(X_train, y_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('kneighborsregressor', KNeighborsRegressor())])

In [99]:
# R2 
def evaluation(model):
    prediction = model_pipeline1.predict(X_test)
    
    print("R2={}".format( model_pipeline1.score(X_test,y_test)))

    # MAE
    errors = abs(prediction - y_test)
    print('Mean Absolute Error:', round(np.mean(errors), 2))

    # MAPE
    mape = 100 * (errors / y_test)
    print('Mean Absolute Percentage Error :', round(np.mean(mape), 2), '%.')
    print('Predicted response:', prediction, sep='\n')

In [100]:
knn= KNeighborsRegressor(n_neighbors = 5)

In [101]:
my_model = pickle.load(open("linear_regression.sav","rb"))
evaluation(my_model)

R2=0.8221129836692596
Mean Absolute Error: 32876.63
Mean Absolute Percentage Error : 17.8 %.
Predicted response:
[119480.  339620.  206540.  ... 219000.  152000.  336780.2]